### ISSUE TITLE
Dash component takes some time to rendering

### ISSUE THREAD

**Issue by pandiarajan-i2i** [obipawan/react-native-dash#1]
Hi,

I have used this library for drawing the dashed lines. It works perfectly but it takes time to rendering. 

**My code:**

```
<View style={{flex:1}}>
            <Dash style={{flex:1,height:1,flexDirection:'row', marginLeft:2, marginRight:16}}  dashColor={'#868686'} dashThickness={2} dashGap={1} dashLength={2}/>
</View>
```

**Comment by obipawan** [comment]
I believe this should be fixed thanks to https://github.com/obipawan/react-native-dash/pull/4
