### ISSUE TITLE
Dash doesn't always re-render when props change

### ISSUE THREAD

**Issue by zoharlevin** [obipawan/react-native-dash#10]
i have a props value for the width of the Dash, something like this:
`Dash style={{width: myWidth}}...`

but the component doesn't seem to always re-render when the `myWidth` value changes.
am I missing something here?

**Comment by obipawan** [comment]
Thanks a ton for reporting and fixing this @zoharlevin  :)

Available in [0.0.7](https://github.com/obipawan/react-native-dash/releases/tag/v0.0.7)
