### ISSUE TITLE
Dash line looks like 2 px width in iOS

### ISSUE THREAD

**Issue by StanislavSergeev** [obipawan/react-native-dash#14]
I am using this package in my project and tested with both iPhone and Android.
I set width as 1px, and in Android it works fine, but in iOS it looks like 2px even though I set as 1 px.

**Comment by clytras** [comment]
@StanislavSergeev  I was facing the same issue, but I realized that I have to use the `dashThickness` property like this:

`<Dash style={{width: '100%', height:1}} dashThickness={1} />`

Then I have the same line thickness on both iOS and Android.
