### ISSUE TITLE
rounded dots instead of dashes

### ISSUE THREAD

**Issue by RobbyAI** [obipawan/react-native-dash#2]
I tried to fork your repository to add a 'rounded' property to allow the creation of rounded dots instead of the default straight lines dashes but it seems that you have restricted the forks access so here is my add-on to Dash.js

LINE 19, 20
`let borderRadius = rounded ? 100 : 0;`
`let overflow = rounded ? 'hidden' : 'visible';`

LINE 33:
`<View key={i} style={{backgroundColor, width, height, marginRight, marginBottom, borderRadius, overflow}}/>`

LINE 49
`rounded: React.PropTypes.bool`

LINE 57
`rounded: false`

**Comment by obipawan** [comment]
Hey @superbibi 

Thanks for the addition!
I haven't introduced any restrictions to the repo myself. What do you see when you try to fork?

**Comment by RobbyAI** [comment]
From either Github for Desktop 
![screen shot 2017-04-13 at 9 20 57 am](https://cloud.githubusercontent.com/assets/1777906/24994895/124f9ee2-202d-11e7-83f2-304a5274a9de.png)
where the push button stay grey.

![screen shot 2017-04-13 at 9 21 15 am](https://cloud.githubusercontent.com/assets/1777906/24994906/1e23121c-202d-11e7-95a4-b117e7db7f29.png)

or Atom:

![screen-shot-2017-04-13-at-9 40 36-am](https://cloud.githubusercontent.com/assets/1777906/24994970/5b0b7dd6-202d-11e7-8456-271e4499e70b.png)

But I'm probably doing something wrong.

**Comment by obipawan** [comment]
Ah I see. You'll need to first fork the repo :) and push your changes to your fork and then submit a PR here. please refer https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by RobbyAI** [comment]
:/ My bad...
I have two GitHub accounts and I'm not logged in with the same on the web and on my laptop IDE

Fork submit.
