### ISSUE TITLE
Height of Dash not automatic scale with it's parent

### ISSUE THREAD

**Issue by TechGuyVN** [obipawan/react-native-dash#23]
Hi,

When i set flex:1 Dash height full screen, only work when i set height is constant , exp 100 
how can dash auto scale by height of it's parent

**Comment by obipawan** [comment]
If you have a nested layout, you'd need to typically set `flex: 1` to each of the node leading to the `Dash` component. Dash simply uses the onLayout to measure the set height | width depending on the `flexDirection`
