### ISSUE TITLE
index.d.ts should be in the release package

### ISSUE THREAD

**Issue by ClementRivaille** [obipawan/react-native-dash#26]
I'm currently using react-native-dash in a Typescript project, and it works great! However, due to **index.d.ts** not being included in the module, the exported component is just typed as *any*. I have to manually add the content of *index.d.ts* into my project for it to work.

This file should be included as well in the the next release, in order to have an optimal use with TS.

**Comment by obipawan** [comment]
Hi @ClementRivaille thanks for reporting!
This is my bad, I missed making a release. Now available on [v0.0.11](https://github.com/obipawan/react-native-dash/releases/tag/v0.0.11)

**Comment by ClementRivaille** [comment]
That fixed the issue! However, it created another error (at compilation):
```
Failed to compile.
C:/[...]/node_modules/react-native-dash/dist/index.js
Module not found: Can't resolve './util' in 'C:\[...]\node_modules\react-native-dash\dist'
```
This might be due to the JS compilation added in 0.0.10. Maybe another issue should be created?

**Comment by obipawan** [comment]
@ClementRivaille, could you try this on [v0.0.11](https://github.com/obipawan/react-native-dash/releases/tag/v0.0.11)? This release patches this bug

**Comment by ClementRivaille** [comment]
My bad, I wasn't up to date! It does fix it indeed.
