### ISSUE TITLE
dashColor removed from v0.0.4

### ISSUE THREAD

**Issue by garthenweb** [obipawan/react-native-dash#5]
in https://github.com/obipawan/react-native-dash/commit/1b2a1c9296bf73ee513bd0534872ddd574b194ab the `dashColor` property was removed from the API, the only remaining references are in the `PropType` declaration and in the readme.

Was this an intended step or an accident?

I would like to keep the `dashColor` because it feels more natural than passing a `backgroundColor` into the `dashStyle` property.

**Comment by obipawan** [comment]
That was a miss. It was intentionally removed as `dashColor` felt redundant when you can get it done with the `dashStyle`. Although, I'm open to it being included again as a prop (which can be overridden by `dashStyle`)
